baseURL = "https://ewoodbury.github.io/ewoodbury.com/"
title = "Ethan Woodbury"
copyright = "Copyright Â© 2024, Ethan Woodbury"
languageCode = "en-US"
theme = ["etch", "hugo-shortcode-gallery"]

[params]
  Author = "Ethan Woodbury"
  Description = "Ethan Woodbury's Website"
  dark = "off"
  highlight = true

  # Contact/social-network identifiers for social icons
  EmailAddress = "ethwoodbury@gmail.com"
  GitHubUser = "ewoodbury"
  TwitterUser = "etwoodbury"

[imaging.exif]
    includeFields = ".*"

[[menu.main]]
name = "About"
url = "/"
weight = 1

[[menu.main]]
name = "Photos"
url = "/photos"
weight = 1